# Generated by Django 5.2.4 on 2025-08-10 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, help_text='Biografía del autor', null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(blank=True, default='autores/default-author.png', null=True, upload_to='autores/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(default='fas fa-tag', help_text='Clase de icono Font Awesome', max_length=50),
        ),
        migrations.AddField(
            model_name='noticia',
            name='activa',
            field=models.BooleanField(default=True, help_text='Noticia visible en el sitio'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen principal de la noticia', null=True, upload_to='noticias/'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticias.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ImagenNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='noticias.noticia')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
